title: "Edgardo | Espacio Profesional y Personal"
description: "Cátedras de Ingeniería y Espacio Personal"

# Tema nativo ultra-limpio y altamente compatible
theme: jekyll-theme-minimal

# Forzamos la paleta de colores inyectando estilos CSS directamente
# para asegurar que tome el azul y cian de la UTN Avellaneda
inline_css: >
  header { background-color: #005a9c !important; }
  .project-name { color: #ffffff !important; }
  .project-tagline { color: #008294 !important; }
  a { color: #005a9c; }
  .btn { background-color: #008294 !important; border-color: #008294 !important; }
